version: '3'
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/api
    expose:
      - "3000"
    ports:
      - "3000:3000"
  ui:
    build:
      context: ./ui
  db:
    build:
      context: ./db
